#pragma config(Sensor, in1,    xAccel,         sensorAccelerometer)
#pragma config(Sensor, in2,    yAccel,         sensorAccelerometer)
#pragma config(Motor,  port1,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           frontRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           backRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// LHS Robotics Autonomous Code 2018-2019
	wait1Msec(200);

	int instY;
	int threshold = 3;
	int threshold2 = 10;
	int waitTime = 25;
	int yBias = abs(SensorValue[yAccel]);

	do
	{
		instY = abs(SensorValue[yAccel]) - yBias;
		wait1Msec(waitTime);
	}
	while(instY < threshold);

  motor[frontRightMotor] = -127;
  motor[backRightMotor]  = 127;
  //Left side of the robot is controlled by the left joystick, Y-axis
  motor[frontLeftMotor] = -100;
 	motor[backLeftMotor]  = 100;

 	clearTimer(T1);

 	yBias = abs(SensorValue[yAccel]);

 	wait(0.5);

 	do
	{
		instY = abs(SensorValue[yAccel]) - yBias;
		wait1Msec(waitTime);
	}
	while(instY < threshold);

	motor[frontRightMotor] = 0;
  motor[backRightMotor]  = 0;
  //Left side of the robot is controlled by the left joystick, Y-axis
  motor[frontLeftMotor] = 0;
 	motor[backLeftMotor]  = 0;

 	int time = time1[T1] / 1000;

 	wait(0.5);

 	motor[frontRightMotor] = 127;
  motor[backRightMotor]  = -127;
  //Left side of the robot is controlled by the left joystick, Y-axis
  motor[frontLeftMotor] = 100;
 	motor[backLeftMotor]  = -100;

 	wait(time);

 	motor[frontRightMotor] = 0;
  motor[backRightMotor]  = 0;
  //Left side of the robot is controlled by the left joystick, Y-axis
  motor[frontLeftMotor] = 0;
 	motor[backLeftMotor]  = 0;

 	wait(0.5);

  motor[frontRightMotor] = -127;
  motor[backRightMotor]  = 127;
  //Left side of the robot is controlled by the left joystick, Y-axis
  motor[frontLeftMotor] = 100;
 	motor[backLeftMotor]  = -100;

 	wait(0.75);

	while(1 == 1)
  {
    motor[frontRightMotor] = -vexRT[Ch2];
    motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[frontLeftMotor] = -vexRT[Ch3];
   	motor[backLeftMotor]  = vexRT[Ch3];
  }



}


static void temp()
{
	int speedFront = -127;
	int speedBack = 127;

	motor[frontRightMotor] = speedFront;
  motor[backRightMotor]  = speedBack;
  ////////////
  motor[frontLeftMotor] = speedFront;
  motor[backLeftMotor]  = speedBack;
  ////////////
  wait(1.0);
  ////////////
  motor[frontRightMotor] = speedFront;
  motor[backRightMotor]  = speedBack;
  ////////////
  motor[frontLeftMotor] = -speedFront;
  motor[backLeftMotor]  = -speedBack;
  ////////////
  wait(1.0);
  motor[frontRightMotor] = speedFront;
  motor[backRightMotor]  = speedBack;
  ////////////
  motor[frontLeftMotor] = speedFront;
  motor[backLeftMotor]  = speedBack;
}
