#pragma config(Sensor, in1,    xAccel,         sensorAccelerometer)
#pragma config(Sensor, in2,    yAccel,         sensorAccelerometer)
#pragma config(Sensor, dgtl2,  clawEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           backLeftMotor, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           stasis,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           frontRightMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           backRightMotor, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
	wait1Msec(200);
  bStopTasksBetweenModes = true;
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void driveForward(int rSpeed, int lSpeed)
{
  motor[frontRightMotor] = -rSpeed;
  motor[backRightMotor]  = rSpeed;
  motor[frontLeftMotor] = -lSpeed;
 	motor[backLeftMotor]  = lSpeed;
}

void driveBackward(int rSpeed, int lSpeed)
{
	motor[frontRightMotor] = rSpeed;
  motor[backRightMotor]  = -rSpeed;
  motor[frontLeftMotor] = lSpeed;
 	motor[backLeftMotor]  = -lSpeed;
}

void driveStop()
{
	motor[frontRightMotor] = 0;
  motor[backRightMotor]  = 0;
  motor[frontLeftMotor] = 0;
 	motor[backLeftMotor]  = 0;
}

void turnL(int rSpeed, int lSpeed)
{
	motor[frontRightMotor] = -rSpeed;
  motor[backRightMotor]  = rSpeed;
  motor[frontLeftMotor] = lSpeed;
 	motor[backLeftMotor]  = -lSpeed;
}

void turnR(int rSpeed, int lSpeed)
{
	motor[frontRightMotor] = rSpeed;
  motor[backRightMotor]  = -rSpeed;
  motor[frontLeftMotor] = -lSpeed;
 	motor[backLeftMotor]  = lSpeed;
}

void Skills()
{
	// LHS Robotics Autonomous Code 2018-2019
	wait1Msec(200);
	//SensorValue[yAccel] = 0;
	int instY;
	int threshold = 6;
	int threshold2 = 10;
	int waitTime = 25;
	int yBias = abs(SensorValue[yAccel]);
	int leftSpeed = 65;
  int rightSpeed = 127;

	driveForward(rightSpeed, leftSpeed);

 	clearTimer(T1);

 	yBias = abs(SensorValue[yAccel]);

 	wait(1);

 	do
	{
		instY = abs(SensorValue[yAccel]) - yBias;
		wait1Msec(waitTime);
		//yBias = abs(SensorValue[yAccel]);
	}
	while(instY < threshold);

  driveStop();

 	int time = time1[T1];

 	wait(0.5);

	driveBackward(rightSpeed, leftSpeed);

 	wait1Msec(time);

 	driveStop();

 	wait(0.5);

  turnR(rightSpeed, leftSpeed);

 	wait(0.65);

 	driveStop();

 	SensorValue[clawEncoder] = 0;

 	while(SensorValue[clawEncoder] < 130)
	{
		motor[claw] = 127;
	}

	motor[claw] = 0;

 	driveForward(rightSpeed, leftSpeed);

 	wait(1.75);

 	driveStop();

 	SensorValue[clawEncoder] = 0;

 	while(SensorValue[clawEncoder] > -30)
	{
		motor[claw] = -127;
	}

	motor[claw] = 0;
}

void Red()
{
	// LHS Robotics Autonomous Code 2018-2019
	wait1Msec(200);
	//SensorValue[yAccel] = 0;
	int instY;
	int threshold = 6;
	int threshold2 = 10;
	int waitTime = 25;
	int yBias = abs(SensorValue[yAccel]);
	int leftSpeed = 65;
  int rightSpeed = 127;

	driveForward(rightSpeed, leftSpeed);

 	clearTimer(T1);

 	yBias = abs(SensorValue[yAccel]);

 	wait(1);

 	do
	{
		instY = abs(SensorValue[yAccel]) - yBias;
		wait1Msec(waitTime);
		//yBias = abs(SensorValue[yAccel]);
	}
	while(instY < threshold);

  driveStop();

 	int time = time1[T1];

 	wait(0.5);

	driveBackward(rightSpeed, leftSpeed);

 	wait1Msec(time);

 	driveStop();

 	wait(0.5);

  turnR(rightSpeed, leftSpeed);

 	wait(0.5);

 	driveStop();

 	SensorValue[clawEncoder] = 0;

 	while(SensorValue[clawEncoder] < 130)
	{
		motor[claw] = 127;
	}

	motor[claw] = 0;

 	driveForward(rightSpeed, leftSpeed);

 	wait(1.75);

 	driveStop();

 	SensorValue[clawEncoder] = 0;

 	while(SensorValue[clawEncoder] > -30)
	{
		motor[claw] = -127;
	}

	motor[claw] = 0;
}

void Blue()
{
		// LHS Robotics Autonomous Code 2018-2019
	wait1Msec(200);
	//SensorValue[yAccel] = 0;
	int instY;
	int threshold = 6;
	int threshold2 = 10;
	int waitTime = 25;
	int yBias = abs(SensorValue[yAccel]);
	int leftSpeed = 65;
  int rightSpeed = 127;

	driveForward(rightSpeed, leftSpeed);

 	clearTimer(T1);

 	yBias = abs(SensorValue[yAccel]);

 	wait(1);

 	do
	{
		instY = abs(SensorValue[yAccel]) - yBias;
		wait1Msec(waitTime);
		//yBias = abs(SensorValue[yAccel]);
	}
	while(instY < threshold);

  driveStop();

 	int time = time1[T1];

 	wait(0.5);

	driveBackward(rightSpeed, leftSpeed);

 	wait1Msec(time);

 	driveStop();

 	wait(0.5);

  turnL(rightSpeed, leftSpeed);

 	wait(0.5);

 	driveStop();

 	SensorValue[clawEncoder] = 0;

 	while(SensorValue[clawEncoder] < 130)
	{
		motor[claw] = 127;
	}

	motor[claw] = 0;

 	driveForward(rightSpeed, leftSpeed);

 	wait(1.75);

 	driveStop();

 	SensorValue[clawEncoder] = 0;

 	while(SensorValue[clawEncoder] > -30)
	{
		motor[claw] = -127;
	}

	motor[claw] = 0;
}

task autonomous()
{
	Skills();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task drive()
{
	while(true)
	{
		//Right side of the robot is controlled by the right joystick, Y-axis
    motor[frontRightMotor] = -vexRT[Ch2];
    motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[frontLeftMotor] = -vexRT[Ch3];
   	motor[backLeftMotor]  = vexRT[Ch3];
  }
}

task clawRun()
{
	while(true)
	{
		///////////////////////a

    if(vexRT[Btn8R] == 1)
    {
    	SensorValue[clawEncoder] = 0;

    	/*while(SensorValue[clawEncoder] < 130)
			{
				motor[claw] = 127;
			}*/

			motor[claw] = 127;

			wait(0.5);

			motor[claw] = 0;
    }

    else if(vexRT[Btn8L] == 1)
    {
    	SensorValue[clawEncoder] = 0;

    	/*while(SensorValue[clawEncoder] > -130)
    	{
    		motor[claw] = -127;
    	}*/

			motor[claw] = -127;

			wait(0.5);

			motor[claw] = 0;
    }

    ///////////////////////b

    if(vexRT[Btn7R] == 1)
    {
    	SensorValue[clawEncoder] = 0;

    	/*while(SensorValue[clawEncoder] < 30)
			{
				motor[claw] = 127;
			}*/

			motor[claw] = 127;

			wait(0.20);

			motor[claw] = 0;

    }

    else if(vexRT[Btn7L] == 1)
    {
    	SensorValue[clawEncoder] = 0;

    	/*while(SensorValue[clawEncoder] > -30)
    	{
    		motor[claw] = -127;
    	}*/

    	motor[claw] = 127;

			wait(0.20);

    	motor[claw] = 0;
    }
  }
}

task usercontrol()
{
  // User control code here, inside the loop

	//int servoInitial = motor[claw];
  bool stasisOn = false;

	startTask(drive);
	startTask(clawRun);

  while (true)
  {
    ///////////////////////

    if(vexRT[Btn5U] == 1)
    {
    	motor[stasis] = 127;
    	stasisOn = true;
    }

    else if(vexRT[Btn5D] == 1)
    {
    	motor[stasis] = -127;
    	stasisOn = false;
    }

    else if(stasisOn)
    {
    	motor[stasis] = 15;
    }

    else
    {
    	motor[stasis] = 0;
    }

    ///////////////////////

    if(vexRT[Btn6U] == 1)
    {
    	motor[lift] = 127;
    }

    else if(vexRT[Btn6D] == 1)
    {
    	motor[lift] = -127;
    }

    else
    {
    	motor[lift] = 0;
    }

  }
}
