#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Controler Code

	This is the code provided on Canvas for POE 
	
	Controlls 2 motors 




*/ 

void ControllerCode(void)
	{
		while(1 == 1)
		  {
		    motor[leftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;  // (y + x)/2
		    motor[rightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;  // (y - x)/2
		  }
	}
task main()
{
	ControllerCode();


}
