#pragma config(Motor,  port2,           controlMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           testMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members:
  Date:
  Section:


  Task Description:


  Pseudocode:

*/
void MotorTest(void)
	{
		startMotor(controlMotor, 127);
		startMotor(testMotor, 127);
		wait(10);
		stopMotor(controlMotor);
		startMotor(controlMotor);

	}


task main()
{                                     //Program begins, insert code within curly braces
	MotorTest();



}
