#pragma config(Motor,  port1,           leftB,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftF,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
