#pragma config(Motor,  port2 ,           test,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[test] = vexRT[Ch2] + vexRT[Ch1];
	}

}
