#pragma config(Motor,  port1,           test1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           test,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Sensor, dgtl2,  clawEncoder,    sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//	motor[test1] = 127;
//	motor[test] = 127;
	SensorValue[clawEncoder] = 0;
	while(SensorValue[clawEncoder] > -310)
	{
		motor[claw] = -127;
	}

}
