#pragma config(Motor,  port1,           test1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           test,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[test1] = 127;
	motor[test] = 127;
	while(true)
	{

	}

}
